print ("3==3")
print (3==3)
print ("hat" == "hat")
print ("hat" != "hat")
print ( "abc" < "fgh")
print ( "fred" < "albert")
print ( "a < ab")
print ("a" < "ab")
print ("a" > "ab")
val = 7-4
print (val)